openapi: 3.0.0
info:
  title: Account Management API
  version: 1.0.0
paths:
  /api/create_account:
    post:
      summary: Create a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountCreateRequest'
      responses:
        '201':
          description: Account successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountCreateResponse'
              examples:
                success:
                  value:
                    success: true
                    reason: ""
                failure:
                  value:
                    success: false
                    reason: "Invalid username length"
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountCreateResponse'
  /api/verify_account:
    post:
      summary: Verify account credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountVerifyRequest'
      responses:
        '200':
          description: Account verification result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountVerifyResponse'
              examples:
                success:
                  value:
                    success: true
                    reason: ""
                failure:
                  value:
                    success: false
                    reason: "Invalid credentials"
        '429':
          description: Too many attempts, try again later
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyAttemptsResponse'
components:
  schemas:
    AccountCreateRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    AccountCreateResponse:
      type: object
      properties:
        success:
          type: boolean
        reason:
          type: string
    AccountVerifyRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    AccountVerifyResponse:
      type: object
      properties:
        success:
          type: boolean
        reason:
          type: string
    TooManyAttemptsResponse:
      type: object
      properties:
        detail:
          type: string
      required:
        - detail
